version: '3.7'
services:
  postgres:
    build:
      context: db
      dockerfile: Dockerfile
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    links:
      - postgres
    depends_on:
      - postgres
    container_name: backend
    ports:
      - '4000:4000'
    build:
      context: server-demo
      dockerfile: Dockerfile
      args:
        - POSTGRES_URL=${POSTGRES_URL}
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      - ./server-demo:/app
      - /app/node_modules
      - /app/prisma
  frontend:
    container_name: frontend
    ports:
      - '3000:3000'
    build:
      context: my-app
      dockerfile: Dockerfile
    environment:
      BACKEND_URL: ${BACKEND_URL}
    volumes:
      - ./my-app:/app
      - /app/node_modules
      - /app/.next
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
volumes:
  postgres: ~
